import anthropic
from anthropic.types import ToolUseBlock
from openai import OpenAI
from dotenv import load_dotenv
import os

load_dotenv()

client = anthropic.Client(api_key=os.getenv("ANTHROPIC_API_KEY"))
openai_client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

def script_agent(section : str, topic : str):

    messages = [{"role": "user", "content" : f"Section: {section}\n Topic : {topic}"}]

    response = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=2000,
        system=f"You are an expert ielts question creator. Create a script for conversation for {section} and {topic}. Keep the script strictly under 3500 characters so it can be converted to speech as this is a requirement.",
        messages=messages
    )

    with open("script.txt", "w", encoding="utf-8") as f:
        f.write(response.content[0].text)

    return response.content[0].text

def question_agent(script : str):

    messages = [{"role":"user", "content": script}]

    response = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=2000,
        system=f"You are an expert ielts question creator. Generate 10 questions for the following question types: multiple choice, fill in the blanks, true/false/not given, short answers.",
        messages=messages
    )

    with open("questions.txt", "w", encoding="utf-8") as f:
        f.write(response.content[0].text)
        
    return response.content[0].text

def tts_agent(script : str):
    print(f"Script length: {len(script)}")
    response = openai_client.audio.speech.create(
        model="tts-1",
        voice="fable",
        input=script
    )

    response.stream_to_file("output.mp3")

    return "Audio saved to output.mp3"

orchestrator_tools = [
    {
        "name": "script_agent",
        "description" : "Create a conversation script.",
        "input_schema": {
            "type":"object",
            "properties": {
                "section": {"type":"string", "description":"The section of the question."},
                "topic": {"type":"string", "description":"The topic of the question."}
            },
            "required": ["section","topic"]
        }
    },
    {
        "name": "question_agent",
        "description": "Create questions based on the script.",
        "input_schema": {
            "type":"object",
            "properties": {
                "script": {"type":"string", "description":"The script for the question."}
            },
            "required":["script"]
        }
    },
    {
        "name": "tts_agent",
        "description": "Convert the IELTS script to speech. Always pass the full script generated by script_agent as the input.",
        "input_schema": {
            "type": "object",
            "properties": {
                "script": {"type": "string", "description": "The full script text generated by script_agent to convert to audio"}
            },
            "required": ["script"]
        }
    }
]

def orchestrator(section : str, topic : str):
    messages = [{"role": "user", "content" : f"Section: {section}\n Topic : {topic}"}]

    response = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=2000,
        tools=orchestrator_tools,
        system="You are an orchestrator. Follow this exact order: 1) Call script_agent to generate a script, 2) Call question_agent passing the script, 3) Call tts_agent passing the same script from step 1. Always pass the script text between agents.",
        messages=messages
    )

    while response.stop_reason != "end_turn":
        tool_results = []
        for block in response.content:
            if isinstance(block, ToolUseBlock):
                if block.name == "script_agent":
                    tool_result = script_agent(**block.input)
                elif block.name == "question_agent":
                    tool_result = question_agent(**block.input)
                elif block.name == "tts_agent":
                    tool_result = tts_agent(**block.input)
                
                tool_results.append({
                    "type": "tool_result",
                    "tool_use_id": block.id,
                    "content": tool_result
                })
        
        messages.append({"role": "assistant", "content": response.content})
        messages.append({"role": "user", "content": tool_results})

        response = client.messages.create(
            model="claude-haiku-4-5",
            max_tokens=2000,
            tools=orchestrator_tools,
            system="You are an orchestrator. Follow this exact order: 1) Call script_agent to generate a script, 2) Call question_agent passing the script, 3) Call tts_agent passing the same script from step 1. Always pass the script text between agents.",
            messages=messages
        )

    return response.content[0].text

result = orchestrator("Section 1 - Conversation (2 people)", "renting an apartment")
print(result)